#ifndef MEMMAP_H
#define MEMMAP_H

#define LAYER0_MAP_MEM 0
#define LAYER0_MAP_MEM_BANK 1

#define LAYER1_MAP_MEM 4096
#define LAYER1_MAP_MEM_BANK 1

#define TILE_MEM 8192
#define TILE_EMPTY_MEM TILE_MEM
#define TILE_SET_1_MEM TILE_EMPTY_MEM + 256
#define TILE_MEM_BANK 1

#define SPRITE_MEM 0
#define SPRITE_MEM_BANK 0

#define SPRITE_MEM_PLAYER 0
#define SPRITE_MEM_PLAYER_BULLET SPRITE_MEM_PLAYER + 1280
#define SPRITE_MEM_SNAKE SPRITE_MEM_PLAYER + 1536
#define SPRITE_MEM_BEE SPRITE_MEM_SNAKE + 1024

#define TILES_ACROSS 64
#define TILES_DOWN 32
#define TILES_SCREEN_ACROSS 40
#define TILES_SCREEN_DOWN 30
#define TILE_PIXEL_WIDTH 16
#define TILE_PIXEL_HEIGHT 16

#endif